DROP TABLE IF EXISTS `USERS`;
CREATE TABLE `USERS` (

ID BIGINT(20) NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(45) DEFAULT NULL,
PASSWORD VARCHAR(45) DEFAULT NULL,
NAME VARCHAR(45) DEFAULT NULL,
USERTYPE VARCHAR(45) DEFAULT NULL,

PRIMARY KEY (`ID`) 
);